name: Build LaTeX document
on: 
  [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: guia.tex
          working_directory: ejercicios
      - name: Delete latest release
        if: success()
        uses: ame-yu/action-delete-latest-release@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: "latest"
          artifacts: "ejercicios/guia.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
